version: "3.3"
services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_DB: people
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    volumes: 
      - postgres_volume:/var/lib/postgres/data
  app:
     container_name: app
     build: .
     ports: 
      - 8080:8080
     environment:
       database_host_name: postgres
     depends_on: 
      - postgres

volumes:
  postgres_volume: